[package]
name = "wonderful"
version = "0.1.0"
authors = ["Jeremy Rodi <me@medcat.me>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
discord = "0.8"
postgres = "0.15"
clap = "2.26"
log = "0.3"
simplelog = "^0.4.2"
bitflags = "1.0"
